### PR TITLE
Switch from travis to Github Actions and setup bors

### PR DESCRIPTION
**Pull request by therealprof**
Signed-off-by: Daniel Egger <daniel@eggers-club.de>

### CODE REVIEW

**Comment by eldruin** [comment]
I believe this should build now if you rebase.

**Comment by eldruin** [comment]
I think this should only build on stable but not attempt to run the tests since they need nightly.

**Comment by therealprof** [comment]
Yeah, need to make the tests conditional somehow. This is clearly less than ideal to have CI depend on a nightly version.

**Comment by therealprof** [comment]
@ryankurte @ithinuel Can I get an approval here?

**Comment by eldruin** [comment]
Yes. One thing that bugs me specially is that `await!` includes `yield` in its expansion and I am not sure what kind of error you would get if attempting to use it on Rust stable. Probably something pretty weird.
I will have a look at adding a `build.rs` to only include it on nightly.

**Comment by therealprof** [comment]
@eldruin You should be able to approve this now. Want to give it a try? ;)

**Pull request merged**
